#!/usr/bin/env bash

GOOGLE_CLIENT_ID=$1
GOOGLE_CLIENT_SECRET=$2
JWT_TOKEN_SECRET=$3
DATABASE_PASSWORD=$4
DATABASE_USERNAME=$5
DATABASE_NAME=$6
DATABASE_HOST=$7
DATABASE_PORT=$8
UPLOAD_LOCATION=$9
FIREBASE_PROJECT_ID=${10}
FIREBASE_PRIVATE_KEY=${11}
FIREBASE_CLIENT_EMAIL=${12}
REDIS_HOST=${13}
REDIS_PORT=${14}
CACHE_TTL=${15}
EXPORT_LOCATION=${16}
DATABASE_LOGGING=${17}
CACHE_REFRESH_TOKEN_TTL=${18}
CI_MERGE_REQUEST_TARGET_BRANCH_NAME=${19}

PORT=3003
NODE_ENV=development
if [ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "production" ]
then 
  PORT=3001
  NODE_ENV=production
fi

docker rm -f eco-api-cd

set -ex

docker load -i eco-api.tar

docker run -d --name eco-api-cd \
  --network host \
  -e LOG_LEVEL="debug" \
  -e DATABASE_HOST="$DATABASE_HOST" \
  -e DATABASE_NAME="$DATABASE_NAME" \
  -e DATABASE_USERNAME="$DATABASE_USERNAME" \
  -e DATABASE_PORT="$DATABASE_PORT" \
  -e GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
  -e GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
  -e JWT_TOKEN_SECRET="$JWT_TOKEN_SECRET" \
  -e DATABASE_PASSWORD="$DATABASE_PASSWORD" \
  -e UPLOAD_LOCATION="$UPLOAD_LOCATION" \
  -e FIREBASE_PROJECT_ID="$FIREBASE_PROJECT_ID" \
  -e FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----$FIREBASE_PRIVATE_KEY-----END PRIVATE KEY-----" \
  -e FIREBASE_CLIENT_EMAIL="$FIREBASE_CLIENT_EMAIL" \
  -e REDIS_HOST="$REDIS_HOST" \
  -e REDIS_PORT="$REDIS_PORT" \
  -e CACHE_TTL="$CACHE_TTL" \
  -e EXPORT_LOCATION="$EXPORT_LOCATION" \
  -e DATABASE_LOGGING="$DATABASE_LOGGING" \
  -e CACHE_REFRESH_TOKEN_TTL="$CACHE_REFRESH_TOKEN_TTL" \
  -e NODE_ENV="$NODE_ENV" \
  -e PORT="$PORT" \
  eco-api

docker exec -t eco-api-cd sh -c "npm run migration:run"
docker exec -t eco-api-cd sh -c "npm run seed:run"